version: '3.8'

services:
  psgan-webapp:
    build: ../../
    container_name: psgan-makeup-app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - PYTHONPATH=/app/src/models:/app/src/utils
    volumes:
      # Mount logs directory for persistence
      - ../../logs:/app/logs
      # Mount results for persistence
      - ../../temp/datasets:/app/temp/datasets
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    name: psgan-network
